
import ifcopenshell
import ifcopenshell.api
import ifcopenshell.guid
import uuid
import math
from typing import List, Dict, Any, Tuple
from backend.core.bim_state import BIMProjectState, BIMElement, ObjectType, Vector3, Room

class IFCCompiler:
    """
    Translates VestaCode BIMProjectState into an Industry Foundation Classes (IFC4) file.
    This enables export to Revit, ArchiCAD, and other BIM software.
    """

    def __init__(self, project: BIMProjectState):
        self.project = project
        self.ifc_file = ifcopenshell.file(schema="IFC4")
        self.owner_history = None
        self.context = None
        self.site = None
        self.building = None
        self.storey = None
        
        # Maps for relationships
        self.element_map: Dict[str, Any] = {}

    def compile(self, output_path: str = "project.ifc"):
        """Main execution method to generate the IFC file."""
        self._init_project_structure()
        self._create_elements()
        self._create_spaces() # New: Create Rooms
        self._save_file(output_path)
        return output_path

    def _init_project_structure(self):
        """Sets up the IFC Project, Site, Building, and Storey."""
        # 1. Project
        project = self.ifc_file.createIfcProject(
            GlobalId=ifcopenshell.guid.new(),
            OwnerHistory=None,
            Name=self.project.name or "Vesta Project",
            Description="Generated by VestaCode Agent"
        )

        # 2. Units & Context
        unit_assignment = self.ifc_file.createIfcUnitAssignment([
            self.ifc_file.createIfcSIUnit(None, "LENGTHUNIT", None, "METRE"),
            self.ifc_file.createIfcSIUnit(None, "AREAUNIT", None, "SQUARE_METRE"),
            self.ifc_file.createIfcSIUnit(None, "VOLUMEUNIT", None, "CUBIC_METRE"),
            self.ifc_file.createIfcSIUnit(None, "PLANEANGLEUNIT", None, "RADIAN")
        ])
        project.UnitsInContext = unit_assignment

        # Geometric Context (3D)
        self.context = self.ifc_file.createIfcGeometricRepresentationContext(
            ContextType="Model",
            CoordinateSpaceDimension=3,
            Precision=1e-5,
            WorldCoordinateSystem=self._create_axis2placement3d((0.0, 0.0, 0.0)),
            TrueNorth=self._create_direction((0.0, 1.0))
        )

        # 3. Site
        self.site = self.ifc_file.createIfcSite(
            GlobalId=ifcopenshell.guid.new(),
            Name="Vesta Site",
            CompositionType="ELEMENT"
        )
        self._add_rel_aggregates(project, self.site)

        # 4. Building
        self.building = self.ifc_file.createIfcBuilding(
            GlobalId=ifcopenshell.guid.new(),
            Name="Main Building",
            CompositionType="ELEMENT"
        )
        self._add_rel_aggregates(self.site, self.building)

        # 5. Storey (Level 1)
        self.storey = self.ifc_file.createIfcBuildingStorey(
            GlobalId=ifcopenshell.guid.new(),
            Name="Level 1",
            Elevation=0.0
        )
        self._add_rel_aggregates(self.building, self.storey)

    def _create_elements(self):
        """Iterates through BIMProjectState elements and creates IFC entities."""
        for el in self.project.elements:
            if el.type == ObjectType.WALL:
                self._create_wall(el)
            elif el.type == ObjectType.DOOR:
                self._create_door(el)
            elif el.type == ObjectType.WINDOW:
                self._create_window(el)
            elif el.type == ObjectType.FURNITURE:
                self._create_furniture(el)

    def _create_spaces(self):
        """Create IfcSpace entities from Room polygons."""
        if not self.project.rooms:
            return

        for room in self.project.rooms:
            # Create Space Geometry (Extruded Polygon)
            # 1. Convert polygon points to IFC cartesian points
            points = []
            for pt in room.polygon:
                # Map Vesta X/Z to IFC X/Y
                points.append(self.ifc_file.createIfcCartesianPoint((float(pt[0]), float(pt[1]))))
            
            # Close the loop
            if points[0] != points[-1]:
                points.append(points[0])

            # 2. Create Polyline
            polyline = self.ifc_file.createIfcPolyline(points)
            
            # 3. Create Arbitrary Closed Profile
            profile = self.ifc_file.createIfcArbitraryClosedProfileDef(
                ProfileType="AREA",
                OuterCurve=polyline
            )

            # 4. Extrude (Height of room, e.g., 2.8m)
            solid = self.ifc_file.createIfcExtrudedAreaSolid(
                SweptArea=profile,
                Position=self._create_axis2placement3d((0.0, 0.0, 0.0)),
                ExtrudedDirection=self._create_direction((0.0, 0.0, 1.0)),
                Depth=2.8
            )

            # 5. Representation
            rep = self.ifc_file.createIfcShapeRepresentation(
                ContextOfItems=self.context,
                RepresentationIdentifier="Body",
                RepresentationType="SweptSolid",
                Items=[solid]
            )
            product_def = self.ifc_file.createIfcProductDefinitionShape(Representations=[rep])

            # 6. IfcSpace Entity
            space = self.ifc_file.createIfcSpace(
                GlobalId=self._get_guid(room.id),
                Name=room.name,
                ObjectPlacement=self._create_local_placement((0.0, 0.0, 0.0)), # Placed at origin relative to storey
                Representation=product_def,
                LongName=room.name,
                CompositionType="ELEMENT"
            )

            self._add_rel_contained_in_spatial_structure(space, self.storey)
            self._add_rel_aggregates(self.storey, space) # Spaces are often aggregated into storey

            # Assign properties (e.g., Room Name for tags)
            self._create_property_set(space, "Pset_SpaceCommon", {
                "Reference": room.name,
                "IsExternal": False
            })

    # -------------------------------------------------------------------------
    # Element Creators
    # -------------------------------------------------------------------------

    def _create_wall(self, el: BIMElement):
        placement = self._get_placement(el)
        length = el.dimensions.x
        height = el.dimensions.y
        thickness = el.dimensions.z
        
        # Profile: Rectangle
        profile = self.ifc_file.createIfcRectangleProfileDef(
            ProfileType="AREA", 
            XDim=length, 
            YDim=thickness
        )
        
        solid = self.ifc_file.createIfcExtrudedAreaSolid(
            SweptArea=profile,
            Position=self._create_axis2placement3d((0.0, 0.0, 0.0)),
            ExtrudedDirection=self._create_direction((0.0, 0.0, 1.0)),
            Depth=height
        )
        
        rep = self.ifc_file.createIfcShapeRepresentation(
            ContextOfItems=self.context,
            RepresentationIdentifier="Body",
            RepresentationType="SweptSolid",
            Items=[solid]
        )
        
        product_def = self.ifc_file.createIfcProductDefinitionShape(Representations=[rep])
        
        wall = self.ifc_file.createIfcWallStandardCase(
            GlobalId=self._get_guid(el.id),
            Name=f"Wall-{el.id}",
            ObjectPlacement=placement,
            Representation=product_def
        )
        
        self._add_rel_contained_in_spatial_structure(wall, self.storey)
        self.element_map[el.id] = wall
        
        # Add Material
        self._assign_material(wall, "Generic Wall Material")

    def _create_door(self, el: BIMElement):
        placement = self._get_placement(el)
        width = el.dimensions.x
        height = el.dimensions.y
        depth = 0.1 
        
        profile = self.ifc_file.createIfcRectangleProfileDef(ProfileType="AREA", XDim=width, YDim=depth)
        solid = self.ifc_file.createIfcExtrudedAreaSolid(
            SweptArea=profile,
            Position=self._create_axis2placement3d((0.0, 0.0, 0.0)),
            ExtrudedDirection=self._create_direction((0.0, 0.0, 1.0)),
            Depth=height
        )
        rep = self.ifc_file.createIfcShapeRepresentation(
            ContextOfItems=self.context,
            RepresentationIdentifier="Body",
            RepresentationType="SweptSolid",
            Items=[solid]
        )
        product_def = self.ifc_file.createIfcProductDefinitionShape(Representations=[rep])
        
        door = self.ifc_file.createIfcDoor(
            GlobalId=self._get_guid(el.id),
            Name=f"Door-{el.id}",
            ObjectPlacement=placement,
            Representation=product_def,
            OverallHeight=height,
            OverallWidth=width
        )
        
        self._add_rel_contained_in_spatial_structure(door, self.storey)
        self.element_map[el.id] = door

    def _create_window(self, el: BIMElement):
        placement = self._get_placement(el)
        width = el.dimensions.x
        height = el.dimensions.y
        depth = 0.1
        
        profile = self.ifc_file.createIfcRectangleProfileDef(ProfileType="AREA", XDim=width, YDim=depth)
        solid = self.ifc_file.createIfcExtrudedAreaSolid(
            SweptArea=profile,
            Position=self._create_axis2placement3d((0.0, 0.0, 0.0)),
            ExtrudedDirection=self._create_direction((0.0, 0.0, 1.0)),
            Depth=height
        )
        rep = self.ifc_file.createIfcShapeRepresentation(
            ContextOfItems=self.context,
            RepresentationIdentifier="Body",
            RepresentationType="SweptSolid",
            Items=[solid]
        )
        product_def = self.ifc_file.createIfcProductDefinitionShape(Representations=[rep])
        
        window = self.ifc_file.createIfcWindow(
            GlobalId=self._get_guid(el.id),
            Name=f"Window-{el.id}",
            ObjectPlacement=placement,
            Representation=product_def,
            OverallHeight=height,
            OverallWidth=width
        )
        
        self._add_rel_contained_in_spatial_structure(window, self.storey)
        self.element_map[el.id] = window

    def _create_furniture(self, el: BIMElement):
        placement = self._get_placement(el)
        width = el.dimensions.x
        height = el.dimensions.y
        depth = el.dimensions.z
        
        profile = self.ifc_file.createIfcRectangleProfileDef(ProfileType="AREA", XDim=width, YDim=depth)
        solid = self.ifc_file.createIfcExtrudedAreaSolid(
            SweptArea=profile,
            Position=self._create_axis2placement3d((0.0, 0.0, 0.0)),
            ExtrudedDirection=self._create_direction((0.0, 0.0, 1.0)),
            Depth=height
        )
        rep = self.ifc_file.createIfcShapeRepresentation(
            ContextOfItems=self.context,
            RepresentationIdentifier="Body",
            RepresentationType="SweptSolid",
            Items=[solid]
        )
        product_def = self.ifc_file.createIfcProductDefinitionShape(Representations=[rep])
        
        item_type = el.metadata.get("item_type", "Furniture")
        # Use IfcBuildingElementProxy for better SketchUp compatibility (easier component replacement)
        furn = self.ifc_file.createIfcBuildingElementProxy(
            GlobalId=self._get_guid(el.id),
            Name=item_type,
            ObjectPlacement=placement,
            Representation=product_def,
            CompositionType="ELEMENT"
        )
        
        self._add_rel_contained_in_spatial_structure(furn, self.storey)
        self.element_map[el.id] = furn

        # Add PSETs for Revit Schedule
        props = {
            "ItemType": item_type,
            "Cost": el.metadata.get("cost", 0.0),
            "Style": el.metadata.get("style_tag", "Standard"),
            "ModelURL": el.model_url or ""
        }
        self._create_property_set(furn, "Pset_FurnitureCommon", props)
        
        # Add Material if known
        if "material" in el.material_properties:
            self._assign_material(furn, el.material_properties["material"])

    # -------------------------------------------------------------------------
    # Helpers
    # -------------------------------------------------------------------------

    def _save_file(self, path: str):
        self.ifc_file.write(path)
        print(f"IFC file written to {path}")

    def _get_guid(self, element_id: str) -> str:
        return ifcopenshell.guid.new()

    def _create_axis2placement3d(self, point_coords: Tuple[float, float, float], 
                                 axis: Tuple[float, float, float] = (0., 0., 1.), 
                                 ref_direction: Tuple[float, float, float] = (1., 0., 0.)):
        location = self.ifc_file.createIfcCartesianPoint(point_coords)
        axis_dir = self.ifc_file.createIfcDirection(axis)
        ref_dir = self.ifc_file.createIfcDirection(ref_direction)
        return self.ifc_file.createIfcAxis2Placement3D(location, axis_dir, ref_dir)
    
    def _create_direction(self, dir_coords: Tuple):
        return self.ifc_file.createIfcDirection(dir_coords)

    def _create_local_placement(self, point_coords):
         location = self.ifc_file.createIfcCartesianPoint(point_coords)
         axis_placement = self.ifc_file.createIfcAxis2Placement3D(location)
         return self.ifc_file.createIfcLocalPlacement(None, axis_placement)

    def _get_placement(self, el: BIMElement):
        # MAPPING: Vesta (Right Handed Y-up) to IFC (Right Handed Z-up)
        # Vesta: x=x, y=height(up), z=depth
        # IFC: x=x, y=depth, z=height(up)
        
        x = el.position.x
        y = el.position.z # Map Vesta Z -> IFC Y
        # Vesta position is center. IFC placement usually at bottom-center or corner depending on profile.
        # Here we place at geometric center of footprint, z=0 (floor)
        z = 0.0 
        
        # Rotation: Vesta Y-axis rotation -> IFC Z-axis rotation
        angle = el.rotation.y
        if angle is None: angle = 0.0
        
        # Direction vector for rotation in XY plane
        dir_x = math.cos(angle)
        dir_y = math.sin(angle)
        
        return self._create_axis2placement3d(
            (x, y, z),
            (0.0, 0.0, 1.0), # Z is up
            (dir_x, dir_y, 0.0) # Rotation in XY plane
        )

    def _add_rel_aggregates(self, parent, child):
        self.ifc_file.createIfcRelAggregates(
            GlobalId=ifcopenshell.guid.new(),
            RelatingObject=parent,
            RelatedObjects=[child]
        )

    def _add_rel_contained_in_spatial_structure(self, product, spatial_structure):
        self.ifc_file.createIfcRelContainedInSpatialStructure(
            GlobalId=ifcopenshell.guid.new(),
            RelatingStructure=spatial_structure,
            RelatedElements=[product]
        )

    def _create_property_set(self, element, pset_name: str, properties: Dict[str, Any]):
        """Creates an IfcPropertySet and assigns it to the element."""
        ifc_props = []
        for name, val in properties.items():
            if isinstance(val, bool):
                ifc_props.append(self.ifc_file.createIfcPropertySingleValue(name, None, self.ifc_file.createIfcBoolean(val), None))
            elif isinstance(val, (int, float)):
                ifc_props.append(self.ifc_file.createIfcPropertySingleValue(name, None, self.ifc_file.createIfcReal(float(val)), None))
            else:
                ifc_props.append(self.ifc_file.createIfcPropertySingleValue(name, None, self.ifc_file.createIfcLabel(str(val)), None))

        pset = self.ifc_file.createIfcPropertySet(ifcopenshell.guid.new(), None, pset_name, None, ifc_props)
        self.ifc_file.createIfcRelDefinesByProperties(ifcopenshell.guid.new(), None, None, None, [element], pset)

    def _assign_material(self, element, material_name: str):
        """Creates and assigns an IfcMaterial."""
        material = self.ifc_file.createIfcMaterial(material_name)
        self.ifc_file.createIfcRelAssociatesMaterial(
            ifcopenshell.guid.new(),
            None,
            "MatAssoc",
            None,
            [element],
            material
        )
