# VestaCode — Custom Vision Model Training Guide
# ================================================
# Train a YOLOv11-seg model to detect walls, doors, windows, and rooms
# from 2D architectural floor plans, then integrate into VestaAgent.
#
# Architecture: YOLOv11 Instance Segmentation (best accuracy/speed tradeoff in 2025)
# Datasets: CubiCasa5K + Roboflow FloorPlan + custom annotations
# Output: ONNX model deployable without GPU dependency

"""
=============================================================================
  PHASE 1: ENVIRONMENT SETUP
=============================================================================
"""

# Step 1: Create a training virtual environment
SETUP_COMMANDS = """
# Create isolated training environment
python3 -m venv ~/vesta_training_env
source ~/vesta_training_env/bin/activate

# Install dependencies
pip install ultralytics              # YOLOv11 (latest Ultralytics)
pip install roboflow                 # Dataset management
pip install albumentations           # Advanced augmentations
pip install supervision              # Visualization
pip install onnxruntime              # ONNX inference
pip install torch torchvision        # PyTorch backend
pip install opencv-python-headless   # Image processing
pip install matplotlib               # Plotting
pip install kaggle                   # For CubiCasa5K download
"""

"""
=============================================================================
  PHASE 2: DATASET ACQUISITION
=============================================================================

Recommended datasets (use ALL for best results):

┌──────────────────────┬──────────┬─────────────────────────────────────────┐
│ Dataset              │ Images   │ Why Use It                              │
├──────────────────────┼──────────┼─────────────────────────────────────────┤
│ CubiCasa5K           │ 5,000    │ Largest, CAD-derived, SVG annotations   │
│ SFPI (Synthetic)     │ 10,000   │ Clean synthetic data, great for pretrain│
│ Roboflow FloorPlan   │ 2,200    │ Pre-annotated YOLO format, doors focus  │
│ CVC-FP               │ 122      │ Real plans, polygon annotations         │
│ Your own (custom)    │ 100-500  │ Domain-specific plans you actually use   │
└──────────────────────┴──────────┴─────────────────────────────────────────┘

Total: ~17,000+ images (excellent for a production model)
"""

# Step 2: Download datasets
DOWNLOAD_DATASETS = """
# --- Option A: CubiCasa5K (Best dataset) ---
# From: https://github.com/CubiCasa/CubiCasa5k
git clone https://github.com/CubiCasa/CubiCasa5k.git ~/datasets/cubicasa5k

# --- Option B: CubiCasa5K YOLO-formatted (Kaggle) ---
# Pre-converted to YOLO format — saves hours of conversion work
# From: https://www.kaggle.com/datasets/cubicasa5k-yolo-formatted
kaggle datasets download -d <dataset-slug> -p ~/datasets/cubicasa5k_yolo

# --- Option C: Roboflow (Ready-to-use YOLO format) ---
# Best for quick start, already annotated
pip install roboflow

# --- Option D: SFPI Synthetic Dataset ---
# From: https://github.com/jmsalash/SFPI-Synthetic-Floor-Plan-Images
git clone https://github.com/jmsalash/SFPI-Synthetic-Floor-Plan-Images.git ~/datasets/sfpi
"""


"""
=============================================================================
  PHASE 3: DATASET PREPARATION
=============================================================================
"""

import os
import json
import shutil
from pathlib import Path


# Define class mapping for VestaAgent
CLASSES = {
    0: "wall",
    1: "door", 
    2: "window",
    3: "room",
    4: "stairs",
    5: "bathroom_fixture",  # toilet, sink, shower
    6: "kitchen_fixture",   # stove, counter
}

NUM_CLASSES = len(CLASSES)


def create_dataset_yaml(dataset_dir: str, output_path: str = "floorplan_dataset.yaml"):
    """
    Create the YOLO dataset configuration file.
    This tells Ultralytics where your data lives and what classes to detect.
    """
    yaml_content = f"""
# VestaCode Floor Plan Detection Dataset
# Generated by training_guide.py

path: {dataset_dir}
train: images/train
val: images/val
test: images/test

# Classes
names:
  0: wall
  1: door
  2: window
  3: room
  4: stairs
  5: bathroom_fixture
  6: kitchen_fixture

# Number of classes
nc: {NUM_CLASSES}
"""
    with open(output_path, "w") as f:
        f.write(yaml_content)
    print(f"✅ Dataset YAML written to {output_path}")
    return output_path


def setup_directory_structure(base_dir: str):
    """
    Create the standard YOLO dataset directory structure:
    
    dataset/
    ├── images/
    │   ├── train/    (70% of images)
    │   ├── val/      (20% of images)
    │   └── test/     (10% of images)
    └── labels/
        ├── train/    (corresponding YOLO .txt labels)
        ├── val/
        └── test/
    """
    for split in ["train", "val", "test"]:
        os.makedirs(f"{base_dir}/images/{split}", exist_ok=True)
        os.makedirs(f"{base_dir}/labels/{split}", exist_ok=True)
    print(f"✅ Directory structure created at {base_dir}")


def convert_cubicasa_svg_to_yolo(svg_dir: str, output_dir: str):
    """
    Convert CubiCasa5K SVG annotations to YOLO format.
    
    CubiCasa SVG format uses polygons with class attributes.
    YOLO format: <class_id> <x1> <y1> <x2> <y2> ... (normalized polygon coords)
    
    For segmentation: class_id x1 y1 x2 y2 x3 y3 ... (polygon vertices)
    For detection:    class_id cx cy w h (bounding box)
    """
    import xml.etree.ElementTree as ET
    from PIL import Image
    
    # CubiCasa category → our class mapping
    CUBICASA_MAP = {
        "Wall": 0,
        "Door": 1,
        "Window": 2,
        "Room": 3,
        "Stairs": 4,
        "Toilet": 5, "Sink": 5, "Bathtub": 5, "Shower": 5,
        "KitchenCounter": 6, "Stove": 6,
    }
    
    svg_files = list(Path(svg_dir).rglob("*.svg"))
    print(f"Found {len(svg_files)} SVG annotation files")
    
    for svg_path in svg_files:
        # Find corresponding image
        img_name = svg_path.stem + ".png"
        img_path = svg_path.parent / img_name
        
        if not img_path.exists():
            continue
            
        img = Image.open(img_path)
        img_w, img_h = img.size
        
        # Parse SVG
        tree = ET.parse(svg_path)
        root = tree.getroot()
        
        labels = []
        # Extract polygons from SVG
        ns = {"svg": "http://www.w3.org/2000/svg"}
        for polygon in root.findall(".//svg:polygon", ns):
            class_name = polygon.get("class", "")
            if class_name not in CUBICASA_MAP:
                continue
                
            class_id = CUBICASA_MAP[class_name]
            points_str = polygon.get("points", "")
            
            if not points_str:
                continue
            
            # Parse polygon points and normalize
            coords = []
            for point in points_str.strip().split():
                x, y = point.split(",")
                # Normalize to 0-1 range
                coords.append(f"{float(x) / img_w:.6f}")
                coords.append(f"{float(y) / img_h:.6f}")
            
            if len(coords) >= 6:  # At least 3 points for a polygon
                labels.append(f"{class_id} " + " ".join(coords))
        
        # Write YOLO label file
        label_path = Path(output_dir) / (svg_path.stem + ".txt")
        with open(label_path, "w") as f:
            f.write("\n".join(labels))
    
    print(f"✅ Converted {len(svg_files)} annotations to YOLO format")


def download_roboflow_dataset(api_key: str, workspace: str, project: str, version: int = 1):
    """
    Download a pre-annotated floor plan dataset from Roboflow.
    This is the FASTEST way to get started.
    
    Recommended projects:
    - "FloorPlan-Detection" (walls, doors, windows)
    - "doors-detection-in-floor-plans" (2200 images, doors focus)
    """
    from roboflow import Roboflow
    
    rf = Roboflow(api_key=api_key)
    project = rf.workspace(workspace).project(project)
    dataset = project.version(version).download("yolov8")  # Works for v11 too
    
    print(f"✅ Dataset downloaded to: {dataset.location}")
    return dataset.location


"""
=============================================================================
  PHASE 4: DATA AUGMENTATION
=============================================================================
Architectural floor plans need special augmentations:
- Rotation (0°, 90°, 180°, 270° — buildings can be oriented any way)
- Scale variations (different zoom levels)
- Line thickness variations (different drawing styles)
- Color jitter (scanned vs digital plans)
- NO vertical/horizontal flip for doors (swing direction matters)
"""

AUGMENTATION_CONFIG = """
# In your training YAML or via Ultralytics CLI:
# These augmentations are automatically applied during training

# Recommended augmentation parameters for floor plans:
hsv_h: 0.015        # Hue shift (minimal — floor plans are mostly B&W)
hsv_s: 0.3          # Saturation shift
hsv_v: 0.3          # Value/brightness shift
degrees: 90.0       # Random rotation (critical for floor plans!)
translate: 0.1       # Random translation
scale: 0.3           # Random scale (0.7x to 1.3x)
shear: 0.0           # No shear (distorts architecture)
perspective: 0.0     # No perspective (floor plans are orthographic)
flipud: 0.0          # No vertical flip (door swings!)  
fliplr: 0.5          # Mirror is OK (left/right symmetric layouts)
mosaic: 1.0          # Mosaic augmentation (mix 4 images)
mixup: 0.1           # MixUp augmentation (blend 2 images)
erasing: 0.1         # Random erasing (simulates occlusion)
"""


"""
=============================================================================
  PHASE 5: MODEL TRAINING
=============================================================================
"""

def train_model(
    dataset_yaml: str = "floorplan_dataset.yaml",
    model_size: str = "m",         # n=nano, s=small, m=medium, l=large, x=xlarge
    epochs: int = 150,
    batch_size: int = 16,
    img_size: int = 1024,          # Floor plans need high resolution
    task: str = "segment",         # "detect" for boxes, "segment" for masks
    device: str = "0",             # GPU device, "cpu" for CPU training
    resume: bool = False,
):
    """
    Train YOLOv11 on floor plan dataset.
    
    Recommended configurations by hardware:
    
    ┌─────────────┬───────────┬──────────┬──────────┬───────────┐
    │ GPU         │ Model     │ Batch    │ ImgSize  │ Time      │
    ├─────────────┼───────────┼──────────┼──────────┼───────────┤
    │ RTX 3060 6G │ yolo11s   │ 8        │ 640      │ ~6 hours  │
    │ RTX 3080 10G│ yolo11m   │ 16       │ 1024     │ ~8 hours  │
    │ RTX 4090 24G│ yolo11l   │ 32       │ 1280     │ ~5 hours  │
    │ A100 40G    │ yolo11x   │ 64       │ 1280     │ ~3 hours  │
    │ CPU only    │ yolo11n   │ 4        │ 640      │ ~48 hours │
    │ Google Colab│ yolo11m   │ 16       │ 1024     │ ~12 hours │
    └─────────────┴───────────┴──────────┴──────────┴───────────┘
    """
    from ultralytics import YOLO

    # Load pretrained model (transfer learning from COCO)
    if task == "segment":
        model = YOLO(f"yolo11{model_size}-seg.pt")  # Segmentation model
    else:
        model = YOLO(f"yolo11{model_size}.pt")        # Detection model

    # Train
    results = model.train(
        data=dataset_yaml,
        epochs=epochs,
        batch=batch_size,
        imgsz=img_size,
        device=device,
        
        # Optimizer
        optimizer="AdamW",
        lr0=0.001,           # Initial learning rate
        lrf=0.01,            # Final learning rate factor
        weight_decay=0.0005,
        warmup_epochs=5,
        
        # Augmentation (floor-plan specific)
        degrees=90.0,        # Critical: floor plans can be any orientation
        flipud=0.0,          # No vertical flip
        fliplr=0.5,          # Horizontal mirror is OK
        mosaic=1.0,
        
        # Architecture
        close_mosaic=15,     # Disable mosaic last 15 epochs for fine-tuning
        
        # Output
        project="runs/floorplan",
        name=f"yolo11{model_size}_{task}_{epochs}ep",
        
        # Performance
        workers=8,
        cache=True,          # Cache images in RAM for speed
        amp=True,            # Mixed precision training
        
        # Resume from checkpoint
        resume=resume,
        
        # Validation
        val=True,
        plots=True,          # Generate training plots
        save=True,
        save_period=10,      # Save checkpoint every 10 epochs
    )
    
    print(f"\n✅ Training complete!")
    print(f"📊 Best mAP@50: {results.results_dict.get('metrics/mAP50(B)', 'N/A')}")
    print(f"📁 Best model: {results.save_dir}/weights/best.pt")
    
    return results


"""
=============================================================================
  PHASE 6: MODEL EVALUATION & EXPORT
=============================================================================
"""

def evaluate_model(model_path: str, dataset_yaml: str):
    """Evaluate trained model on test set."""
    from ultralytics import YOLO
    
    model = YOLO(model_path)
    metrics = model.val(data=dataset_yaml, split="test")
    
    print(f"\n📊 Evaluation Results:")
    print(f"   mAP@50:     {metrics.box.map50:.4f}")
    print(f"   mAP@50-95:  {metrics.box.map:.4f}")
    print(f"   Precision:   {metrics.box.p.mean():.4f}")  
    print(f"   Recall:      {metrics.box.r.mean():.4f}")
    
    # Per-class results
    print(f"\n   Per-Class mAP@50:")
    for i, name in CLASSES.items():
        if i < len(metrics.box.ap50):
            print(f"   {name:20s}: {metrics.box.ap50[i]:.4f}")
    
    return metrics


def export_model(model_path: str, format: str = "onnx"):
    """
    Export model for deployment.
    
    Formats:
    - onnx:     CPU inference, no GPU needed (recommended for VestaAgent)
    - torchscript: PyTorch deployment
    - engine:   TensorRT (NVIDIA GPU, fastest)
    - openvino: Intel CPU optimized
    - coreml:   Apple Silicon
    """
    from ultralytics import YOLO
    
    model = YOLO(model_path)
    
    exported = model.export(
        format=format,
        imgsz=1024,
        half=False,       # FP32 for CPU (use True for GPU)
        simplify=True,    # Simplify ONNX graph
        dynamic=True,     # Dynamic batch size
    )
    
    print(f"✅ Model exported to: {exported}")
    return exported


"""
=============================================================================
  PHASE 7: INTEGRATION WITH VESTAAGENT
=============================================================================
"""

# This is the inference module that replaces the LLM-based vision agent
# with your custom trained model.

def create_custom_vision_agent():
    """
    Generate the custom VisionAgent that uses YOUR trained model
    instead of an LLM for floor plan analysis.
    """
    
    agent_code = '''
import numpy as np
import cv2
import uuid
import math
from typing import List, Optional
from ultralytics import YOLO
from backend.agents.vision.schema import VisionExtraction, DetectedWall, DetectedOpening
from backend.core.bim_state import BIMElement, ObjectType, Vector3


# Class mapping (must match training)
CLASS_NAMES = {0: "wall", 1: "door", 2: "window", 3: "room", 
               4: "stairs", 5: "bathroom_fixture", 6: "kitchen_fixture"}


class CustomVisionAgent:
    """
    Custom-trained vision model for floor plan analysis.
    Uses YOLOv11-seg instead of LLM for deterministic, fast detection.
    
    Advantages over LLM:
    - 10-50x faster inference
    - Deterministic results (same input = same output)
    - No API costs 
    - Works offline
    - Pixel-accurate segmentation masks
    """
    
    def __init__(self, model_path: str = "models/floorplan_best.pt"):
        self.model = YOLO(model_path)
        self.confidence_threshold = 0.4
        self.iou_threshold = 0.5
        # Pixels-to-meters scale (calibrate with known measurements)
        self.scale = 0.02  # Default: 1 pixel = 0.02 meters (50px per meter)
    
    def _estimate_scale(self, image: np.ndarray, detections) -> float:
        """
        Estimate pixel-to-meter scale from detected elements.
        Uses standard door width (0.8m) as reference.
        """
        door_widths_px = []
        for det in detections:
            if det["class"] == "door":
                w = det["bbox"][2] - det["bbox"][0]
                h = det["bbox"][3] - det["bbox"][1]
                door_widths_px.append(min(w, h))  # Door width is shorter dimension
        
        if door_widths_px:
            avg_door_px = np.mean(door_widths_px)
            # Standard door = 0.8m
            self.scale = 0.8 / avg_door_px
            
        return self.scale
    
    async def process_plan(self, image_bytes: bytes) -> VisionExtraction:
        """Process floor plan image and extract geometry."""
        
        # 1. Decode image
        is_pdf = image_bytes.startswith(b"%PDF")
        if is_pdf:
            import fitz
            doc = fitz.open(stream=image_bytes, filetype="pdf")
            page = doc.load_page(0)
            pix = page.get_pixmap(matrix=fitz.Matrix(2, 2))
            img_array = np.frombuffer(pix.samples, dtype=np.uint8).reshape(
                pix.height, pix.width, pix.n
            )
            doc.close()
        else:
            img_array = np.frombuffer(image_bytes, dtype=np.uint8)
            img_array = cv2.imdecode(img_array, cv2.IMREAD_COLOR)
        
        # 2. Run inference
        results = self.model.predict(
            img_array,
            conf=self.confidence_threshold,
            iou=self.iou_threshold,
            imgsz=1024,
            verbose=False
        )[0]
        
        # 3. Parse detections
        detections = []
        for i, box in enumerate(results.boxes):
            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            x1, y1, x2, y2 = box.xyxy[0].tolist()
            
            det = {
                "class": CLASS_NAMES.get(cls_id, "unknown"),
                "confidence": conf,
                "bbox": [x1, y1, x2, y2],
                "mask": None
            }
            
            # Get segmentation mask if available
            if results.masks is not None and i < len(results.masks):
                det["mask"] = results.masks[i].xy[0].tolist()  # Polygon points
            
            detections.append(det)
        
        # 4. Estimate scale from door detections
        scale = self._estimate_scale(img_array, detections)
        
        # 5. Convert to VestaAgent format
        walls = []
        openings = []
        room_labels = []
        
        for det in detections:
            x1, y1, x2, y2 = det["bbox"]
            cx = (x1 + x2) / 2 * scale  # Center X in meters
            cy = (y1 + y2) / 2 * scale  # Center Y in meters
            w = (x2 - x1) * scale
            h = (y2 - y1) * scale
            
            if det["class"] == "wall":
                # Determine wall orientation from aspect ratio
                if w > h:
                    # Horizontal wall
                    walls.append(DetectedWall(
                        start=[cx - w/2, cy],
                        end=[cx + w/2, cy],
                        thickness=max(h, 0.1),
                        is_load_bearing=(h > 0.15)  # Thick walls are load-bearing
                    ))
                else:
                    # Vertical wall
                    walls.append(DetectedWall(
                        start=[cx, cy - h/2],
                        end=[cx, cy + h/2],
                        thickness=max(w, 0.1),
                        is_load_bearing=(w > 0.15)
                    ))
            
            elif det["class"] == "door":
                openings.append(DetectedOpening(
                    type="door",
                    position=[cx, cy],
                    width=min(w, h),  # Door width is shorter dimension
                    rotation=0 if w > h else 90
                ))
            
            elif det["class"] == "window":
                openings.append(DetectedOpening(
                    type="window",
                    position=[cx, cy],
                    width=max(w, h),  # Window width is longer dimension
                    rotation=0 if w > h else 90
                ))
            
            elif det["class"] == "room":
                room_labels.append(f"Room at ({cx:.1f}, {cy:.1f})")
        
        # 6. Build extraction result
        avg_confidence = np.mean([d["confidence"] for d in detections]) if detections else 0.5
        
        notes = (
            f"Custom model detected {len(walls)} walls, "
            f"{len([o for o in openings if o.type == 'door'])} doors, "
            f"{len([o for o in openings if o.type == 'window'])} windows. "
            f"Rooms found: {', '.join(room_labels) if room_labels else 'N/A'}. "
            f"Total: {len(room_labels)} rooms. "
            f"Scale: {scale:.4f} m/px."
        )
        
        return VisionExtraction(
            walls=walls if walls else [DetectedWall(start=[0,0], end=[10,0], thickness=0.2, is_load_bearing=True)],
            openings=openings,
            scale_ratio=scale,
            confidence_score=avg_confidence,
            notes=notes
        )
'''
    
    output_path = "backend/agents/vision/custom_agent.py"
    with open(output_path, "w") as f:
        f.write(agent_code)
    print(f"✅ Custom vision agent written to {output_path}")


"""
=============================================================================
  PHASE 8: ANNOTATING YOUR OWN DATA
=============================================================================

If you want to annotate your own floor plans (HIGHLY RECOMMENDED for best results):

1. Use Roboflow (Free tier: 10,000 images)
   - Upload your floor plan images
   - Draw bounding boxes / polygons around walls, doors, windows
   - Export in YOLOv8 format
   - URL: https://app.roboflow.com

2. Use CVAT (Open source, self-hosted)
   - URL: https://github.com/cvat-ai/cvat
   - Best for polygon annotations (wall segmentation)
   - Export in YOLO format

3. Use Label Studio (Open source)
   - URL: https://labelstud.io
   - Supports both boxes and polygons

Annotation Tips for Floor Plans:
- Draw TIGHT bounding boxes around each wall segment
- Mark the ENTIRE door arc (swing area) for doors
- For windows: mark the parallel lines on the wall
- Label internal and external walls separately if possible
- Annotate at least 100-200 plans for decent results
- 500+ plans for production quality
"""


"""
=============================================================================
  PHASE 9: GOOGLE COLAB TRAINING (FREE GPU)
=============================================================================
"""

COLAB_NOTEBOOK = """
# ============================================
# VestaCode Floor Plan Model — Google Colab
# ============================================
# Run this in a Colab notebook with GPU runtime

# Step 1: Install
!pip install ultralytics roboflow

# Step 2: Check GPU
import torch
print(f"GPU: {torch.cuda.get_device_name(0)}")
print(f"VRAM: {torch.cuda.get_device_properties(0).total_mem / 1e9:.1f} GB")

# Step 3: Download dataset (Roboflow example)
from roboflow import Roboflow
rf = Roboflow(api_key="YOUR_ROBOFLOW_API_KEY")
project = rf.workspace("YOUR_WORKSPACE").project("floorplan-detection")
dataset = project.version(1).download("yolov8")

# Step 4: Train
from ultralytics import YOLO
model = YOLO("yolo11m-seg.pt")

results = model.train(
    data=f"{dataset.location}/data.yaml",
    epochs=100,
    batch=16,
    imgsz=1024,
    device=0,
    degrees=90.0,
    flipud=0.0,
    project="floorplan_training",
    name="v1"
)

# Step 5: Evaluate
metrics = model.val()
print(f"mAP@50: {metrics.box.map50:.4f}")

# Step 6: Export
model.export(format="onnx", imgsz=1024, simplify=True)

# Step 7: Download model
from google.colab import files
files.download("floorplan_training/v1/weights/best.pt")
files.download("floorplan_training/v1/weights/best.onnx")
"""


"""
=============================================================================
  PHASE 10: SWITCHING VESTAAGENT TO USE CUSTOM MODEL
=============================================================================
"""

INTEGRATION_GUIDE = """
After training, integrate your model into VestaAgent:

1. Copy your trained model to:
   backend/models/floorplan_best.pt

2. Update backend/core/llm_factory.py to add a "custom" provider:
   
   class LLMProvider(str, Enum):
       GROQ = "groq"
       GEMINI = "gemini"
       CUSTOM_VISION = "custom_vision"  # Your trained model

3. Update the Vision Agent to use CustomVisionAgent when provider is custom:

   # In backend/agents/vision/agent.py
   from backend.agents.vision.custom_agent import CustomVisionAgent
   
   class VisionAgent:
       def __init__(self, model_name=None, use_custom=False):
           if use_custom:
               self.agent = CustomVisionAgent("backend/models/floorplan_best.pt")
           else:
               self.llm = get_llm(agent_name="vision", ...)

4. Update the orchestrator to support the toggle:

   # In graph.py vision_node:
   async def vision_node(state):
       use_custom = os.environ.get("VESTA_VISION_MODEL", "llm") == "custom"
       vision = VisionAgent(use_custom=use_custom)

5. Set environment variable to switch:
   VESTA_VISION_MODEL=custom  → Uses your trained YOLO model
   VESTA_VISION_MODEL=llm     → Uses Groq/Gemini (default)
"""


"""
=============================================================================
  QUICK START — Run this to begin training immediately
=============================================================================
"""

if __name__ == "__main__":
    print("""
    ╔══════════════════════════════════════════════════════════════════╗
    ║  VESTACODE — Custom Vision Model Training Guide                 ║
    ╚══════════════════════════════════════════════════════════════════╝
    
    Recommended training path (fastest to best):
    
    ┌───────────────────────────────────────────────────────────────────┐
    │  LEVEL 1: Quick Start (1-2 hours)                                │
    │  • Download Roboflow FloorPlan dataset (pre-annotated)           │
    │  • Train YOLOv11n on Google Colab (free GPU)                     │
    │  • Good for proof-of-concept                                     │
    ├───────────────────────────────────────────────────────────────────┤
    │  LEVEL 2: Production (1-2 days)                                  │
    │  • Combine CubiCasa5K + Roboflow + SFPI datasets                │
    │  • Train YOLOv11m for 150 epochs                                 │
    │  • Add 100+ custom floor plans from your domain                  │
    │  • Export to ONNX for CPU deployment                             │
    ├───────────────────────────────────────────────────────────────────┤
    │  LEVEL 3: Research-grade (1-2 weeks)                             │
    │  • Full CubiCasa5K + custom annotations                         │
    │  • Train YOLOv11l-seg for instance segmentation                  │
    │  • Hyperparameter tuning with Ultralytics Ray Tune               │
    │  • Multi-scale inference for mixed-resolution plans              │
    │  • Ensemble with LLM for room labeling                          │
    └───────────────────────────────────────────────────────────────────┘
    
    Steps to begin:
    
    1. Run: python3 training_guide.py setup
       → Creates dataset directory structure
    
    2. Download a dataset (see Phase 2)
    
    3. Run: python3 training_guide.py train
       → Trains YOLOv11m-seg model
    
    4. Run: python3 training_guide.py export
       → Exports to ONNX for deployment
    
    5. Copy model to backend/models/ and set:
       VESTA_VISION_MODEL=custom
    """)
    
    import sys
    if len(sys.argv) > 1:
        cmd = sys.argv[1]
        
        if cmd == "setup":
            base = os.path.expanduser("~/datasets/floorplan")
            setup_directory_structure(base)
            create_dataset_yaml(base)
            
        elif cmd == "train":
            train_model(
                dataset_yaml="floorplan_dataset.yaml",
                model_size="m",
                epochs=150,
                batch_size=16,
                img_size=1024,
                task="segment",
            )
            
        elif cmd == "eval":
            evaluate_model(
                model_path="runs/floorplan/yolo11m_segment_150ep/weights/best.pt",
                dataset_yaml="floorplan_dataset.yaml"
            )
            
        elif cmd == "export":
            export_model(
                model_path="runs/floorplan/yolo11m_segment_150ep/weights/best.pt",
                format="onnx"
            )
            
        elif cmd == "agent":
            create_custom_vision_agent()
            
        else:
            print(f"Unknown command: {cmd}")
            print("Usage: python3 training_guide.py [setup|train|eval|export|agent]")
